// resources/js/components/dashboard/problem-card.tsx
import { usePage } from '@inertiajs/react';
import { ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { DifficultyBadge } from '@/components/ui/difficulty-badge';
import { StatusBadge } from '@/components/ui/status-badge';
import { cn } from '@/lib/utils';

interface ProblemCardProps {
    problem: any;
    onLog?: (problem: any) => void;
}

function formatRelativeTime(date: string) {
    const now = new Date();
    const logDate = new Date(date);
    const diffInHours = Math.floor(
        (now.getTime() - logDate.getTime()) / (1000 * 60 * 60),
    );

    if (diffInHours < 1) {
        return 'Just now';
    }

    if (diffInHours < 24) {
        return `${diffInHours}h ago`;
    }

    const diffInDays = Math.floor(diffInHours / 24);

    return `${diffInDays}d ago`;
}

export function ProblemCard({ problem, onLog }: ProblemCardProps) {
    const { auth } = usePage().props as any;
    const preferredPlatform = auth?.preferredPlatform ?? 'leetcode';
    const practiceUrl = preferredPlatform === 'neetcode' && problem.neetcodeUrl
        ? problem.neetcodeUrl
        : problem.leetcodeUrl;
    const isNew = !problem.lastLog;

    return (
        <div
            className={cn(
                'group relative flex cursor-pointer flex-col overflow-hidden rounded-3xl border border-border bg-card p-8 transition-colors hover:border-primary/30',
                isNew ? 'border-l-2 border-l-primary/40' : '',
            )}
            role="button"
            tabIndex={0}
            onClick={() => onLog?.(problem)}
            onKeyDown={(e) => e.key === 'Enter' && onLog?.(problem)}
        >
            <div className="flex h-full flex-col gap-5">
                <div className="flex items-start justify-between gap-3">
                    <span className="mt-0.5 font-mono text-[10px] font-bold tracking-widest text-primary/50 uppercase">
                        #{problem.number}
                    </span>
                    <DifficultyBadge difficulty={problem.difficulty} />
                </div>

                <h3 className="text-xl leading-tight font-black tracking-tight text-foreground uppercase transition-colors group-hover:text-primary">
                    {problem.title}
                </h3>

                {problem.patterns && problem.patterns.length > 0 && (
                    <div className="flex flex-wrap gap-1.5">
                        {problem.patterns.slice(0, 3).map((pattern: string) => (
                            <span
                                key={pattern}
                                className="rounded-md border border-border bg-muted px-2 py-0.5 text-[11px] font-medium tracking-wider text-muted-foreground uppercase"
                            >
                                {pattern}
                            </span>
                        ))}
                        {problem.patterns.length > 3 && (
                            <span className="text-[11px] text-muted-foreground/40">
                                +{problem.patterns.length - 3}
                            </span>
                        )}
                    </div>
                )}

                <div className="mt-auto flex items-center justify-between gap-3 border-t border-border pt-5">
                    <div className="flex min-w-0 items-center gap-2">
                        {problem.lastLog ? (
                            <>
                                <StatusBadge status={problem.lastLog.status} />
                                <span className="tabular truncate font-mono text-[10px] tracking-widest text-muted-foreground uppercase">
                                    {formatRelativeTime(
                                        problem.lastLog.timestamp,
                                    )}
                                </span>
                            </>
                        ) : (
                            <span className="font-mono text-[10px] tracking-widest text-primary/40 uppercase">
                                New
                            </span>
                        )}
                    </div>

                    <div className="flex shrink-0 items-center gap-2">
                        <a
                            href={practiceUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-muted-foreground/50 transition-colors hover:text-primary"
                            onClick={(e) => e.stopPropagation()}
                            aria-label={`Open on ${preferredPlatform === 'neetcode' ? 'NeetCode' : 'LeetCode'}`}
                        >
                            <ExternalLink className="h-4 w-4" />
                        </a>
                        <Button
                            variant="ghost"
                            size="sm"
                            onClick={(e) => {
                                e.stopPropagation();
                                onLog?.(problem);
                            }}
                            className="h-8 !rounded-md border border-border !px-4 !text-[10px] !font-black tracking-widest transition-all hover:border-primary hover:bg-primary hover:text-primary-foreground"
                        >
                            Log
                        </Button>
                    </div>
                </div>
            </div>
        </div>
    );
}

// src/lib/components/dashboard/ProblemCard.svelte
<script lang="ts">
	import Button from '$lib/components/ui/Button.svelte';
	import DifficultyBadge from '$lib/components/ui/DifficultyBadge.svelte';
	import StatusBadge from '$lib/components/ui/StatusBadge.svelte';
	import { ExternalLink } from '@lucide/svelte';
	import type { ProblemWithLogs } from '$lib/types';
	import { openLogModal, openDetailsModal } from '$lib/stores/logsStore';

	let { problem }: { problem: ProblemWithLogs } = $props();

	function formatRelativeTime(date: Date | string) {
		const now = new Date();
		const logDate = new Date(date);
		const diffInHours = Math.floor((now.getTime() - logDate.getTime()) / (1000 * 60 * 60));

		if (diffInHours < 1) return 'Just now';
		if (diffInHours < 24) return `${diffInHours}h ago`;
		const diffInDays = Math.floor(diffInHours / 24);
		return `${diffInDays}d ago`;
	}

	const isNew = $derived(!problem.lastLog);
</script>

<div
	class="group relative flex flex-col overflow-hidden rounded-3xl bg-card border border-border p-8 transition-colors hover:border-primary/30 cursor-pointer
		{isNew ? 'border-l-2 border-l-primary/40' : ''}"
	onclick={() => openDetailsModal(problem)}
	role="button"
	tabindex="0"
	onkeydown={(e) => e.key === 'Enter' && openDetailsModal(problem)}
>
	<div class="flex flex-col h-full gap-5">
		<!-- Header -->
		<div class="flex items-start justify-between gap-3">
			<span class="text-[10px] font-mono text-primary/50 font-bold uppercase tracking-widest mt-0.5">
				#{problem.number}
			</span>
			<DifficultyBadge difficulty={problem.difficulty} />
		</div>

		<h3 class="text-xl font-black text-foreground tracking-tight leading-tight uppercase group-hover:text-primary transition-colors">
			{problem.title}
		</h3>

		<!-- Patterns -->
		{#if problem.patterns.length > 0}
			<div class="flex flex-wrap gap-1.5">
				{#each problem.patterns.slice(0, 3) as pattern (pattern)}
					<span class="text-[11px] font-medium uppercase tracking-wider px-2 py-0.5 rounded-md bg-muted text-muted-foreground border border-border">
						{pattern}
					</span>
				{/each}
				{#if problem.patterns.length > 3}
					<span class="text-[11px] text-muted-foreground/40">+{problem.patterns.length - 3}</span>
				{/if}
			</div>
		{/if}

		<!-- Footer -->
		<div class="mt-auto pt-5 border-t border-border flex items-center justify-between gap-3">
			<div class="flex items-center gap-2 min-w-0">
				{#if problem.lastLog}
					<StatusBadge status={problem.lastLog.status} />
					<span class="text-[10px] font-mono text-muted-foreground uppercase tracking-widest tabular truncate">
						{formatRelativeTime(problem.lastLog.timestamp)}
					</span>
				{:else}
					<span class="text-[10px] font-mono text-primary/40 uppercase tracking-widest">New</span>
				{/if}
			</div>

			<div class="flex items-center gap-2 shrink-0">
				<a
					href={problem.leetcodeUrl}
					target="_blank"
					rel="noopener noreferrer"
					class="text-muted-foreground/50 hover:text-primary transition-colors"
					onclick={(e) => e.stopPropagation()}
					aria-label="Open on LeetCode"
				>
					<ExternalLink class="h-4 w-4" />
				</a>
				<Button
					variant="ghost"
					size="sm"
					onclick={(e) => { e.stopPropagation(); openLogModal(problem); }}
					class="!rounded-md h-8 !px-4 !text-[10px] !font-black tracking-widest border border-border hover:bg-primary hover:text-primary-foreground hover:border-primary transition-all"
				>
					Log
				</Button>
			</div>
		</div>
	</div>
</div>
