// resources/js/components/dashboard/zero-state.tsx
import { CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';

export function ZeroState() {
    return (
        <div className="flex flex-col items-center justify-center py-20 text-center">
            <div className="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl border border-primary/20 bg-primary/10">
                <CheckCircle2 className="h-8 w-8 text-primary" />
            </div>
            <h2 className="mb-2 text-xl font-black tracking-tight text-foreground uppercase">
                All caught up
            </h2>
            <p className="mb-8 font-medium text-muted-foreground">
                Nothing due today. Log a new problem to keep building.
            </p>
            <Button
                className="!rounded-md border border-white/10 px-6 !text-[10px] !font-black tracking-widest transition-all hover:border-primary hover:bg-primary hover:text-primary-foreground"
                variant="ghost"
            >
                Log a problem
            </Button>
        </div>
    );
}

// src/lib/components/dashboard/ZeroState.svelte
<script lang="ts">
	import Button from '$lib/components/ui/Button.svelte';
	import { CheckCircle2 } from '@lucide/svelte';
	import { openSearchModal } from '$lib/stores/logsStore';
</script>

<div class="flex flex-col items-center justify-center py-20 text-center">
	<div class="mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10 border border-primary/20">
		<CheckCircle2 class="h-8 w-8 text-primary" />
	</div>
	<h2 class="mb-2 text-xl font-black text-foreground uppercase tracking-tight">
		All caught up
	</h2>
	<p class="mb-8 text-muted-foreground font-medium">
		Nothing due today. Log a new problem to keep building.
	</p>
	<Button
		onclick={openSearchModal}
		class="!rounded-md px-6 !text-[10px] !font-black tracking-widest border border-white/10 hover:bg-primary hover:text-primary-foreground hover:border-primary transition-all"
		variant="ghost"
	>
		Log a problem
	</Button>
</div>
